### ISSUE TITLE
gem 'rails-assets-cdn' fails

### ISSUE THREAD

**Issue by ghost** [cmer/rails-assets-cdn#1]
`gem 'rails-assets-cdn'` does not resolve to a valid gem file.

`Could not find gem 'rails-assets-cdn (>= 0) ruby' in the gems available on this machine.`

**Comment by cmer** [comment]
Thanks. Fixed.

**Comment by ghost** [comment]
Thank you! Great gem.

**Comment by cmer** [comment]
The kind of thing I wished existed, so I built it!
